# Generated by Django 5.2.11 on 2026-02-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='body',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='date',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='title',
        ),
    ]
